name: obsidianraider
author: [klaudijus]
main: net.cactusdev.obsidianraider.ObsidianRaiderMain
version: 1.2
spigot: 24194
load: POSTWORLD
api-version: 1.14

commands:
  obsidianr:
    description: Fully reload the plugin.
    permission: <plugin name>.reload
    permission-message: You don't have <permission> to use this command.
    aliases: [or, obbyr, oraider, obbyraider]

permissions:
  obsidianraider.reload:
    description: Reload the plugin access.
    default: op